#!/usr/bin/bash

tmux select-pane -t 1
tmux send 'g++ -o ~/Desktop/.temp/cpp_obj "$(<~/Desktop/.temp/.filename.txt)" ' ENTER;  
tmux select-pane -t 0
tmux send ENTER;
tmux select-pane -t 1
tmux send ~/Desktop/.temp/cpp_obj ENTER;
